name: Pull assign

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: planningcenter/pull-assign-action@wm/tweaks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
