name: Plus One

on:
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: planningcenter/plus-one-action@wm/fix-comment-clobbering
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
