name: Plus One

on:
  pull_request:
    types: [review_request_removed]
  pull_request_review:
    types: [dismissed, submitted]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: planningcenter/plus-one-action@wm/fix-comment-clobbering
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
